In [1]:
import torch
import numpy as np

In [2]:
from torch.autograd import Variable

In [3]:
x_tensor = torch.randn(10, 5)

In [4]:
x_tensor

tensor([[ 0.8278, -0.8196,  0.3715,  0.3231, -0.8315],
        [-1.1035, -0.9832, -0.1999, -0.8288, -1.3531],
        [-0.6482, -0.9090,  0.9939,  0.2289, -0.6369],
        [ 0.3987, -1.2560, -1.5282,  0.5175,  1.0432],
        [ 0.7080,  1.2488,  0.6724,  0.4897,  0.7415],
        [-0.4513, -0.1611,  1.2078,  2.5314, -0.4320],
        [ 0.1570, -0.4941, -0.1987, -0.6694, -1.9089],
        [ 1.1715, -0.1046, -2.9325,  1.8701, -0.0917],
        [ 1.4088, -0.2721, -0.2106, -0.4918,  0.2973],
        [-0.4711,  0.4987,  1.9117, -0.4768,  0.0490]])

In [5]:
y_tensor = torch.randn(10, 5)

In [6]:
x = Variable(x_tensor, requires_grad = True)

In [7]:
y = Variable(y_tensor, requires_grad = True)

In [8]:
x

tensor([[ 0.8278, -0.8196,  0.3715,  0.3231, -0.8315],
        [-1.1035, -0.9832, -0.1999, -0.8288, -1.3531],
        [-0.6482, -0.9090,  0.9939,  0.2289, -0.6369],
        [ 0.3987, -1.2560, -1.5282,  0.5175,  1.0432],
        [ 0.7080,  1.2488,  0.6724,  0.4897,  0.7415],
        [-0.4513, -0.1611,  1.2078,  2.5314, -0.4320],
        [ 0.1570, -0.4941, -0.1987, -0.6694, -1.9089],
        [ 1.1715, -0.1046, -2.9325,  1.8701, -0.0917],
        [ 1.4088, -0.2721, -0.2106, -0.4918,  0.2973],
        [-0.4711,  0.4987,  1.9117, -0.4768,  0.0490]], requires_grad=True)

In [9]:
sum = torch.sum(x + y)

In [10]:
sum.data

tensor(0.9637)

In [11]:
sum.grad_fn

In [12]:
sum.backward()

In [13]:
x.grad

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
y.grad

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
x2 = Variable(torch.Tensor([2]), requires_grad = True)

In [16]:
y2 = x2 + 2

In [17]:
z1 = y2 ** 2 +3

In [18]:
print(z1)

tensor([19.], grad_fn=<AddBackward0>)


In [19]:
z1.backward()

In [20]:
print(x2.grad)

tensor([8.])


In [21]:
x3 = Variable(torch.randn(10, 20), requires_grad = True)

In [22]:
y3 = Variable(torch.randn(10, 5), requires_grad = True)

In [23]:
w = Variable(torch.randn(20, 5), requires_grad = True)

In [24]:
out = torch.mean(y3 - torch.matmul(x3, w))

In [25]:
out.backward()

In [26]:
x3.grad

tensor([[ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
      

In [27]:
print(y3.grad)

tensor([[0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200]])


In [28]:
print(x3.grad)

tensor([[ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
          0.0089, -0.0005,  0.0051,  0.0165],
        [ 0.0355, -0.0152, -0.0332,  0.0506,  0.0721,  0.0163,  0.0242,  0.0556,
          0.0063, -0.0327, -0.0104,  0.0357, -0.0549, -0.0716,  0.0866,  0.0555,
      

In [29]:
m = Variable(torch.FloatTensor([[5, 6]]), requires_grad = True)

In [30]:
n = Variable(torch.zeros(1, 2))

In [31]:
print(m, n)

tensor([[5., 6.]], requires_grad=True) tensor([[0., 0.]])


In [32]:
n[0, 0] = m[0, 0] ** 2

In [33]:
n[0, 1] = m[0, 1] **3

In [34]:
print(n)

tensor([[ 25., 216.]], grad_fn=<CopySlices>)


In [36]:
n.backward(torch.ones_like(n))

In [37]:
print(m.grad)

tensor([[ 10., 108.]])


In [38]:
x4 = Variable(torch.FloatTensor([3]), requires_grad = True)

In [39]:
y4 = x4*2 + x4**2 + 3

In [40]:
y4

tensor([18.], grad_fn=<AddBackward0>)

In [41]:
y4.backward(retain_graph=True)

In [42]:
x4.grad

tensor([8.])

In [43]:
y4.backward()

In [44]:
x4.grad

tensor([16.])

In [45]:
x5 = Variable(torch.randn(1, 10))

In [46]:
prev_h = Variable(torch.randn(1, 20))

In [47]:
W_h = Variable(torch.randn(20, 20))

In [51]:
W_x = Variable(torch.randn(20, 10))

In [52]:
i2h = torch.mm(W_x, x5.t())

In [53]:
h2h = torch.mm(W_h, prev_h.t())