In [2]:
import torch
from torch.autograd import Variable

In [3]:
x = Variable(torch.ones(2, 2), requires_grad = True)

In [4]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
y = Variable(torch.ones(2, 2), requires_grad = True)

In [7]:
y

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [12]:
x + y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [8]:
z = torch.sum(x + y)

In [9]:
print(z.data)

tensor(8.)


In [10]:
z.backward()

In [11]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])
