In [32]:
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
import numpy as np
import pandas as pd

In [3]:
X_train = np.array([[1., -1., 2,] ,
                          [2., 0., 0.,],
                          [0., 1., -1.]])

In [4]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [5]:
min_max_scalar = preprocessing.MinMaxScaler()

In [6]:
min_max_scalar

MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
X_train_minmax = min_max_scalar.fit_transform(X_train)

In [8]:
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [9]:
scaled = preprocessing.scale(X_train)

In [10]:
scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
scaled.mean(axis = 0)

array([0., 0., 0.])

In [12]:
scaled.std(axis = 0)

array([1., 1., 1.])

In [13]:
standardScaler = preprocessing.StandardScaler().fit(X_train)

In [14]:
standardScaler.mean_

array([1.        , 0.        , 0.33333333])

In [15]:
standardScaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [16]:
standardScaler.transform([[-1., 1., 0.]])

array([[-2.44948974,  1.22474487, -0.26726124]])

In [17]:
arr = np.random.randn(20)

In [18]:
factor = pd.cut(arr, 4)

In [19]:
factor

[(-1.787, -0.94], (-0.94, -0.097], (0.746, 1.59], (-0.097, 0.746], (0.746, 1.59], ..., (0.746, 1.59], (0.746, 1.59], (-1.787, -0.94], (-0.94, -0.097], (-0.94, -0.097]]
Length: 20
Categories (4, interval[float64]): [(-1.787, -0.94] < (-0.94, -0.097] < (-0.097, 0.746] < (0.746, 1.59]]

In [20]:
fixedFactor = pd.cut(arr, [-5, -1, 0, 1, 5])

In [21]:
fixedFactor

[(-5, -1], (-1, 0], (1, 5], (0, 1], (1, 5], ..., (0, 1], (1, 5], (-5, -1], (-1, 0], (-1, 0]]
Length: 20
Categories (4, interval[int64]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [22]:
titanicData = pd.read_csv(r'./data/titanic.csv')

In [23]:
titanicData.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [24]:
ParchDummies =  pd.get_dummies(titanicData['Parch'], prefix = 'Parch')

In [25]:
ParchDummies

Parch_0  Parch_1  Parch_2  Parch_3  Parch_4  Parch_5  Parch_6
0          1        0        0        0        0        0        0
1          1        0        0        0        0        0        0
2          1        0        0        0        0        0        0
3          1        0        0        0        0        0        0
4          1        0        0        0        0        0        0
5          1        0        0        0        0        0        0
6          1        0        0        0        0        0        0
7          0        1        0        0        0        0        0
8          0        0        1        0        0        0        0
9          1        0        0        0        0        0        0
10         0        1        0        0        0        0        0
11         1        0        0        0        0        0        0
12         1        0        0        0        0        0        0
13         0        0        0        0        0        1        0
14         1        0        0        0        0        0        0
15         1        0        0        0        0        0        0
16         0        1        0        0        0        0        0
17         1        0        0        0        0        0        0
18         1        0        0        0        0        0        0
19         1        0        0        0        0        0        0
20         1        0        0        0        0        0        0
21         1        0        0        0        0        0        0
22         1        0        0        0        0        0        0
23         1        0        0        0        0        0        0
24         0        1        0        0        0        0        0
25         0        0        0        0        0        1        0
26         1        0        0        0        0        0        0
27         0        0        1        0        0        0        0
28         1        0        0        0        0        0        0
29         1        0        0        0        0        0        0
..       ...      ...      ...      ...      ...      ...      ...
861        1        0        0        0        0        0        0
862        1        0        0        0        0        0        0
863        0        0        1        0        0        0        0
864        1        0        0        0        0        0        0
865        1        0        0        0        0        0        0
866        1        0        0        0        0        0        0
867        1        0        0        0        0        0        0
868        1        0        0        0        0        0        0
869        0        1        0        0        0        0        0
870        1        0        0        0        0        0        0
871        0        1        0        0        0        0        0
872        1        0        0        0        0        0        0
873        1        0        0        0        0        0        0
874        1        0        0        0        0        0        0
875        1        0        0        0        0        0        0
876        1        0        0        0        0        0        0
877        1        0        0        0        0        0        0
878        1        0        0        0        0        0        0
879        0        1        0        0        0        0        0
880        0        1        0        0        0        0        0
881        1        0        0        0        0        0        0
882        1        0        0        0        0        0        0
883        1        0        0        0        0        0        0
884        1        0        0        0        0        0        0
885        0        0        0        0        0        1        0
886        1        0        0        0        0        0        0
887        1        0        0        0        0        0        0
888        0        0        1        0        0    

In [26]:
iris = load_iris()

In [27]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [30]:
X, y = iris.data, iris.target

In [31]:
X.shape

(150, 4)

In [33]:
X_news = SelectKBest(chi2, k = 2).fit_transform(X, y)

In [35]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [34]:
X_news

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,