In [1]:
import tensorflow as tf

/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [53]:
import tensorflow_datasets

In [52]:
!pip install -q tensorflow_datasets

tensorflow-metadata 0.13.0 has requirement protobuf<4,>=3.7, but you'll have protobuf 3.6.1 which is incompatible.
You are using pip version 18.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
tf.__version__

'2.0.0-dev20190505'

In [3]:
tf.executing_eagerly()

True

In [4]:
tf.keras.__version__

'2.2.4-tf'

In [5]:
var = tf.Variable([3, 3])

In [6]:
if tf.test.is_gpu_available():
    print('Running on Gpu')
else:
    print("cpu")

cpu


In [7]:
t1 = tf.Variable([[[0., 1. ,2.], [3., 4., 5.]], [[6., 7., 8.], [9., 10., 11.]]])

In [8]:
t2= tf.Variable(42)

In [9]:
m_o_1 = tf.constant(42)

In [10]:
m_o_1

<tf.Tensor: id=22, shape=(), dtype=int32, numpy=42>

In [11]:
m_o_1.numpy()

42

In [12]:
t3 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9.,10., 11.] ] ])

In [13]:
t3.shape

TensorShape([2, 2, 3])

In [14]:
r1 = tf.reshape(t3, [2, 6])

# reshape

In [15]:
r1

<tf.Tensor: id=34, shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

# dimense

In [16]:
tf.rank(t3)

<tf.Tensor: id=37, shape=(), dtype=int32, numpy=3>

# trans to numpy

In [17]:
tf.size(t3).numpy()

12

In [18]:
tf.size(input = t3).numpy()

12

# data type

In [19]:
t3.dtype

tf.float32

In [20]:
t3*t3

<tf.Tensor: id=47, shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

# broadcast

In [21]:
t3 * 4

<tf.Tensor: id=51, shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

In [22]:
u = tf.constant([[3, 4, 3]])

In [23]:
v = tf.constant([[1, 2, 1]])

# matrix mul

In [24]:
tf.matmul(u, tf.transpose(a = v))

<tf.Tensor: id=57, shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

# dtype cast

In [25]:
i = tf.cast(t1, dtype=tf.int32)

In [26]:
i

<tf.Tensor: id=60, shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

# ragged tensors

In [27]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

In [28]:
ragged

tf.RaggedTensor(values=tf.Tensor([ 5  2  6  1  4 10  7  8  6  7], shape=(10,), dtype=int32), row_splits=tf.Tensor([ 0  4  4  7  8 10], shape=(6,), dtype=int64))

In [29]:
ragged[0, :]

<tf.Tensor: id=90, shape=(4,), dtype=int32, numpy=array([5, 2, 6, 1], dtype=int32)>

In [30]:
ragged[1, :]

<tf.Tensor: id=116, shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [31]:
print(tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6,7],row_splits=[0, 4, 7, 7, 8, 10]))

<tf.RaggedTensor [[5, 2, 6, 1], [4, 10, 7], [], [8], [6, 7]]>


# Squared difference

In [32]:
tf.math.squared_difference([1, 4, 8], 5)

<tf.Tensor: id=166, shape=(3,), dtype=int32, numpy=array([16,  1,  9], dtype=int32)>

# mean

In [33]:
numbers = tf.constant([[4., 5.], [7., 3.]])

In [35]:
realNums = [[4., 5.], [7., 3.]]

In [34]:
tf.reduce_mean(numbers)

<tf.Tensor: id=200, shape=(), dtype=float32, numpy=4.75>

In [36]:
tf.reduce_mean(realNums)

<tf.Tensor: id=328, shape=(), dtype=float32, numpy=4.75>

In [37]:
tf.reduce_mean(numbers, axis = 0)

<tf.Tensor: id=391, shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [38]:
tf.reduce_mean(realNums, axis=1)

<tf.Tensor: id=455, shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

# tensor random

## normal

In [41]:
tf.random.normal( (3,2), mean = 0, stddev =2, dtype=tf.float32, seed=None,name=None)

<tf.Tensor: id=642, shape=(3, 2), dtype=float32, numpy=
array([[-1.6518977 , -1.3635894 ],
       [ 4.438119  , -0.48027262],
       [ 1.8521032 ,  1.0132264 ]], dtype=float32)>

## uniform

In [42]:
tf.random.uniform(shape = (2,4),  minval=0, maxval=None, dtype=tf.float32,seed=None,  name=None)

<tf.Tensor: id=770, shape=(2, 4), dtype=float32, numpy=
array([[0.8764467 , 0.42330015, 0.945634  , 0.24455571],
       [0.10439575, 0.28047502, 0.67182744, 0.9833741 ]], dtype=float32)>

# largest smallest

In [43]:
tf5 = tf.constant([2, 11, 5, 42, 7, 19, 7, 12, 1, 29])

In [44]:
i = tf.argmax(tf5)

In [46]:
i.numpy()

3

In [48]:
min = tf.argmin(tf5).numpy()

In [49]:
min

8

# tf.function

In [50]:
def f1(x, y):    
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)