In [ ]:
# This is an example snippet!
# To create your own, add a new snippet block to the
# snippets.json file in your jupyter nbextensions directory:
# /nbextensions/snippets/snippets.json
import this

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [34]:
def LeastSquareMethod(beProjectedVector,existedVector):
    projectionNum=np.dot(np.linalg.inv(np.dot(beProjectedVector.T,beProjectedVector)),np.dot(beProjectedVector.T,existedVector))
    return projectionNum

In [4]:
nsample = 20

In [5]:
x = np.linspace(0, 10 , nsample)

In [6]:
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
X = sm.add_constant(x)

In [13]:
X

array([[ 1.        ,  0.        ],
       [ 1.        ,  0.52631579],
       [ 1.        ,  1.05263158],
       [ 1.        ,  1.57894737],
       [ 1.        ,  2.10526316],
       [ 1.        ,  2.63157895],
       [ 1.        ,  3.15789474],
       [ 1.        ,  3.68421053],
       [ 1.        ,  4.21052632],
       [ 1.        ,  4.73684211],
       [ 1.        ,  5.26315789],
       [ 1.        ,  5.78947368],
       [ 1.        ,  6.31578947],
       [ 1.        ,  6.84210526],
       [ 1.        ,  7.36842105],
       [ 1.        ,  7.89473684],
       [ 1.        ,  8.42105263],
       [ 1.        ,  8.94736842],
       [ 1.        ,  9.47368421],
       [ 1.        , 10.        ]])

In [14]:
beta = np.array([2, 5])

In [15]:
beta

array([2, 5])

In [17]:
e = np.random.normal(size = nsample)

In [27]:
y = np.dot(X, beta) 

In [28]:
y

array([ 2.        ,  4.63157895,  7.26315789,  9.89473684, 12.52631579,
       15.15789474, 17.78947368, 20.42105263, 23.05263158, 25.68421053,
       28.31578947, 30.94736842, 33.57894737, 36.21052632, 38.84210526,
       41.47368421, 44.10526316, 46.73684211, 49.36842105, 52.        ])

In [35]:
olsModelBySelf = LeastSquareMethod(X, y)

In [21]:
olsModel = sm.OLS(y, X)

In [22]:
res = olsModel.fit()

In [24]:
res.params

array([2.36799528, 4.90637605])

In [26]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.993
Model:                            OLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     2394.
Date:                Sat, 27 Apr 2019   Prob (F-statistic):           1.34e-20
Time:                        02:05:52   Log-Likelihood:                -33.489
No. Observations:                  20   AIC:                             70.98
Df Residuals:                      18   BIC:                             72.97
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.3680      0.587      4.037      0.001       1.136       3.600
x1             4.9064      0.100     48.929      0.000       4.696       5.117
==============================================================================
Omnibus:                        0.694   Durbin-Watson:                   0.926
Prob(Omnibus):                  0.707   Jarque-Bera (JB):                0.480
Skew:                          -0.356   Prob(JB):                        0.787
Kurtosis:                       2.737   Cond. No.                         11.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [37]:
olsModelBySelf

array([2., 5.])